### ISSUE TITLE
The delete account button doesn't work

### ISSUE THREAD

**Issue by teauxfu** [MrDavidRios/remindr#8]
Hey there, I downloaded and made an account to try things out. 
Remindr is a nice concept and a cute app. You've got a star from me!
I did notice however that the delete account button doesn't seem to work 😳
Maybe I'm doing something wrong? 
![image](https://user-images.githubusercontent.com/1144380/115099650-e3756180-9efc-11eb-828e-3e972c3e654f.png)
This dialog just closes without taking an action.
After clicking I can sign out, and still sign back in.
I'm assuming the problem may be in 
https://github.com/MrDavidRios/remindr/blob/5f7bcd2ecc7e1b80020ee4f09b5b1f8441e3c347/src/data.ts#L578
but I'm not sure how to view the console log, so I can't see where specifically the problem might be
Is there a keyboard shortcut for that? I can submit a log if it would help

**Comment by MrDavidRios** [comment]
Hey, thanks for testing the app and letting me know! I released a commit earlier today fixing that issue as it didn't work for me either.

I'll try to release a hotfix in the next few days to fix it, as I'm still dealing with some issues in updating Electron to a newer version.

I currently have a password lock on DevTools since I'm not yet proud of the way it's formatted. Until I remove it, you can use Ctrl + Shift + I and enter this code to open DevTools and send a log: Kr;,$V9=]-5WN^p][cA!7_sgvzVh9F

**Comment by MrDavidRios** [comment]
Try updating the app and see if it works now. If it doesn't, please let me know. 

Thanks again!
